# Generated by Django 3.0.6 on 2020-06-02 03:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenewsFE', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='output',
            name='value',
            field=models.CharField(max_length=1000),
        ),
    ]
